#!/usr/bin/env bash

# Collect per-project rules and update the main authz file


svn_root="/var/svn"
svn_url="file://$svn_root/projects"
svn_authz="$svn_root/authz"

###############################################################################


wd="`dirname $0`"
cd "$wd"

for p in `svn list "$svn_url" | cut -d / -f 1`
do
	f="authz_files/$p"

	(svn export --force "$svn_url/$p/authz" $f 2>&1 | grep -v "doesn't exist") && chmod 600 $f
done

cat << END > authz.tmp
#####################################################
# NEVER modify this file directly!
# This file is generated by script in $wd
# All changes should go to $wd/authz_general
#####################################################

END

# Make authz readable only by the Subversion server user (Apache DAV SVN here)
chmod 600 authz.tmp
chown www:www authz.tmp

./mkauthz.pl authz_general `ls authz_files/` >> authz.tmp 2> err.last
mv authz.tmp "$svn_authz"
